name: CI

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}}}
    steps:
      - uses: actions/checkout@v1
      - name: Set default image tag
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          echo "::set-output name=IMAGE_TAG::${branch}-latest"
      - name: Build the Radix application
        run: |
          docker build -t ghcr.io/satr/edc2021-radix-app-from-external-ci:${{ steps.prep.outputs.IMAGE_TAG }} ./app/
      - name: Push the image to GitHub container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u satr --password-stdin
          docker push ghcr.io/satr/edc2021-radix-app-from-external-ci:${{ steps.prep.outputs.IMAGE_TAG }}
      - name: Deploy API on Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            -a edc2021-radix-app-from-external-ci
            --context playground
            -e deploy-only-example
            -f