name: CI

on:
  push:
    branches:
      - main
      - release

permissions:
  id-token: write

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 7ef841f8-a263-45ea-8993-683cc6817ae2
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: 'Get Azure principal token for Radix'
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: 'Set default image tag'
        run: |
          echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF##*/}-latest)
      - name: Build the Radix application
        run: |
          docker build -t ghcr.io/satr/edc2021-radix-app-from-external-ci:${{ steps.prep.outputs.IMAGE_TAG }} ./app/
      - name: Push the image to GitHub container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u satr --password-stdin
          docker push ghcr.io/satr/edc2021-radix-app-from-external-ci:${{ steps.prep.outputs.IMAGE_TAG }}
      - name: Get environment from branch
        id: getEnvironment
        uses: equinor/radix-github-actions@master
        with:
          args: >
            get config branch-environment
            --from-config
            -b ${GITHUB_REF##*/}
      - name: Deploy API on Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            -a edc2021-radix-app-from-external-ci
            --context playground
            --from-config
            -e ${{ steps.getEnvironment.outputs.result }}
            -f